fun main() {
    //Loops().loopWhile()
    //Loops().loopDoWhile()
    //Loops().loopFor()
    //NullSafety().tryCatch()
    //NullSafety().elvis()
    //Collections().lists()
    //Collections().arrays()
    //Collections().orderLists()
    //Collections().maps()
    //Collections().sets()
    //Functions().functions()
    //Functions().functionParameters()
    //Functions().lambdas()
    //Functions().highOrderFunctions()
    //ScopeFunctions().let()
    ScopeFunctions().with()
}